name: Scaffold Android Platform

on:
  workflow_dispatch:

jobs:
  scaffold:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          
      - name: Create Android Platform
        run: flutter create . --platforms=android
        
      - name: Commit and Push Android Folder
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-generate Android platform files"
          branch: main
